language: php
dist: trusty
sudo: false

matrix:
  include:
  - php: "5.6"
    env:
    - LARAVEL_VERSION=5.4.*
    - PHPUNIT_VERSION=^5.7

install:
- composer require "laravel/framework:${LARAVEL_VERSION}" --no-update -n
- composer require "phpunit/phpunit:${PHPUNIT_VERSION}" --dev --no-update -n
- travis_retry composer install --no-suggest --prefer-dist -n -o

script:
  - vendor/bin/phpunit
